version: '3.8'

services:
  # Service PHP
  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.1-fpm
    container_name: php-fpm
    volumes:
      - ./symfony:/var/www/html
    networks:
      - symfony
    environment:
      - PHP_OPCACHE=1

  # Service Nginx
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./symfony:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - symfony

  # Service MySQL
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony_db
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - symfony

  # Service Composer
  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./symfony:/app
    networks:
      - symfony
    command: bash -c "composer install"

  # Service pour l'installation des outils de qualité
  quality-tools:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.1-cli
    container_name: quality-tools
    volumes:
      - ./symfony:/app
    networks:
      - symfony
    command: bash -c "composer install && composer require --dev phpro/grumphp squizlabs/php_codesniffer phpstan/phpstan phpunit/phpunit phpmd/phpmd"

volumes:
  mysql_data:
    driver: local

networks:
  symfony:
    driver: bridge
